#
# ident	@(#)Makefile.targ 1.3	02/05/21 GED
#
# Makefile.targ
#

distsubdirs:
	@for f in $(SUBDIRS); do \
		(cd $$f; $(MAKE) RELDIR=$(RELDIR)/$$f distlist ) \
	done

distlist:
	@test -n "$(SUBDIRS)" && \
		$(MAKE) RELDIR=$(RELDIR) distsubdirs; true
	@echo $(DISTSRCS:%=$(RELDIR)/%)

distsrcs:	$(DISTSRCS)
