#
# $Id: Makefile.targ,v 1.2 2004/08/27 23:40:12 gdamore Exp $
#
# Makefile.targ
#

distsubdirs:
	@for f in $(SUBDIRS); do \
		(cd $$f; $(MAKE) RELDIR=$(RELDIR)/$$f distlist ) \
	done

distlist:
	@test -n "$(SUBDIRS)" && \
		$(MAKE) RELDIR=$(RELDIR) distsubdirs; true
	@echo $(DISTSRCS:%=$(RELDIR)/%)

distsrcs:	$(DISTSRCS)
