#
# ident	@(#)Makefile 1.10	03/06/03 GED
#
# drv/afe/Makefile
#

TOP=../..

include	../Makefile.common

MODNAME		=	afe
SRCS		=	afe.c
HDRS		=	$(TOP)/inc/sys/afe.h \
			$(TOP)/inc/sys/afeimpl.h \
			$(TOP)/inc/sys/mii.h
LDFLAGS		+=	-dy -Nmisc/gld

include ../Makefile.drv
