#
# $Id: Makefile.common,v 1.2 2004/08/27 23:03:38 gdamore Exp $
#
# drv/Makefile.common
#

include	$(TOP)/Makefile.common

LINTFLAGS	=	-erroff=E_BAD_PTR_CAST_ALIGN
LINTFLAGS	+=	-nsmuxF $(CPPFLAGS)
DDICTFLAGS	=	$(CPPFLAGS)

CPPFLAGS	+=	-I $(TOP)/inc
DEFS		=	-D_KERNEL $(DEBUG)
CPPFLAGS	+=	$(DEFS)
CFLAGS		+=	$($(ISA)_CFLAGS) $(COPTFLAG)
MOD		=	$(TOP)/obj.$(ISA)/$(MODNAME)
OBJS		=	$(SRCS:%.c=$(TOP)/obj.$(ISA)/%.o)
LINTS		=	$(OBJS:%.o=%.ln)
DISTSRCS	=	$(SRCS) Makefile
