#
# ident	@(#)Makefile	1.9	02/05/27 GED
#
# pkg/GEDenetd/Makefile
#

TOP = ../..

include	../Makefile.common

PKGNAME		=	GEDenetd
PKGSRCS		+=	checkinstall postinstall postremove depend

include	../Makefile.pkg
