#
# $Id: Makefile.common,v 1.2 2004/08/27 22:59:23 gdamore Exp $
#
# cmd/Makefile.common
#

include	$(TOP)/Makefile.common

LINTFLAGS	=
LINTFLAGS	+=	$(CPPFLAGS)
CPPFLAGS	+=	-I $(TOP)/inc
CPPFLAGS	+=	$(DEFS) $(DEBUG)
CFLAGS		+=	$($(ISA)_CFLAGS) $(COPTFLAG)
PROG		=	$(TOP)/obj.$(ISA)/$(PROGNAME)
OBJS		=	$(SRCS:%.c=$(TOP)/obj.$(ISA)/%.o)
LINTS		=	$(OBJS:%.o=%.ln)
DISTSRCS	=	$(SRCS) Makefile
