#
# $Id: Makefile,v 1.2 2004/08/28 06:09:46 gdamore Exp $
#
# drv/mxfe/Makefile
#

TOP=../..

include	../Makefile.common

MODNAME		=	mxfe
SRCS		=	mxfe.c
HDRS		=	$(TOP)/inc/sys/mxfe.h \
			$(TOP)/inc/sys/mxfeimpl.h \
			$(TOP)/inc/sys/mii.h
LDFLAGS		+=	-dy -Nmisc/gld

include ../Makefile.drv
