#
# ident	"@(#)Makefile	1.4	03/06/03 GED"
#
# drv/mxfe/Makefile
#

TOP=../..

include	../Makefile.common

MODNAME		=	mxfe
SRCS		=	mxfe.c
HDRS		=	$(TOP)/inc/sys/mxfe.h \
			$(TOP)/inc/sys/mxfeimpl.h \
			$(TOP)/inc/sys/mii.h
LDFLAGS		+=	-dy -Nmisc/gld

include ../Makefile.drv
